### ISSUE TITLE
Explore Extended Profile-related upload issues

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1690] opened 2022-03-02 18:19 UTC
## Overview

Retest the upload errors OAR identified in [this doc](https://docs.google.com/document/d/1Tsq6mNrSDsXlskVuZJe2DhM-15Yxqt4coClgym_ajfM/edit) **that are related to Extended Profile.**

### Describe the solution you'd like

- Retest the upload errors OAR identified in [this doc](https://docs.google.com/document/d/1Tsq6mNrSDsXlskVuZJe2DhM-15Yxqt4coClgym_ajfM/edit) **that are related to Extended Profile.**
- If there are still problems with a specific list, create a new issue to follow up.

**Comment by emilyhu0106** [comment] 2022-03-07 23:39
Notes for errors in the [doc](https://docs.google.com/document/d/1Tsq6mNrSDsXlskVuZJe2DhM-15Yxqt4coClgym_ajfM/edit) and those related to Extended Profile are marked in ✅ 

1. Not related to EP
2. Verified issue, but **not** related to EP:
	- Having issue parsing 8/1318 facilities in .csv and more parsing errors in .xlsx
	- Issues are caused by address being too long or no matching country code
3. Verified, one of the error in bullet point 2, but **not** related to EP:
	- `List index out of range` is caused by a new line (aka. `\n`) in the address field
4. Fixed in PR [#1675](https://github.com/open-apparel-registry/open-apparel-registry/pull/1675)
5. Verified and related to EP  ✅ :
	- `Could not convert string to ‘float’` error is caused by `number_of_workers`
6. Not related to EP
7. Not related to EP
8. Not [reproducible](https://openapparel.org/lists/1524?search=amazing%20square&page=1&rowsPerPage=20) and not related to EP:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/60887686/157136600-a2143b75-0986-47ba-8213-9bf48a1eb70f.png">

10. Not related to EP: Geo-coding failure

**Comment by emilyhu0106** [comment] 2022-03-16 19:48
> @emilyhu0106 - OAR added a new error to the document. Could you take a look?

This issue is not related to extended profile and the comment section is updated accordingly

**Comment by obrienad** [comment] 2022-03-16 20:55
Thanks, Emily!

**Closed** 2022-03-17 19:47 UTC
Labels: task 026-A

**Comment by mariel-oar** [comment] 2022-03-18 14:21
@emilyhu0106 , in the error [doc](https://docs.google.com/document/d/1Tsq6mNrSDsXlskVuZJe2DhM-15Yxqt4coClgym_ajfM/edit), I understand that some of theses errors are not related to EP, but our intention with this ticket is to understand the implications of these error and what the user needs to do to resolve.  Could you help clarify what these mean for the user: 

-  Item 2: "List index out of range is caused by a new line (aka. \n) in the address field" (e.g. does this mean the address is too long?) 
**Question** >> usually this would return ERROR_PARSING, why is this causing a different error? 

- Item 3: Verified issue, but not related to EP:
Having issue parsing 8/1318 facilities in .csv and more parsing errors in .xlsx
Issues are caused by address being too long or no matching country code
**Question** >> usually this would return ERROR_GEOCODING, why is this causing a different error? 

- Item 11: Not related to EP: geocoding issue related to in-accurate address "Plot No. 7/8, U Myuu Street, Myay Taing Block No. 65 (Settmu), Industrial Zone 4, Shwe Pyi Thar Township, Yangon,"
**Question** >> usually this would return ERROR_GEOCODING, why is this causing a different error?

**Comment by obrienad** [comment] 2022-03-18 14:47
Hi Mariel - when you flagged the request to understand the core roots (as reflected in the permanent / resolvable column I added), I should have asked you to create a new ticket accordingly. Emily and I discussed the follow-on component for this work, when we have approval to bill to Task 33.
