### ISSUE TITLE
"adidas" appearing twice as a contributor on a facility

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#924] opened 2019-12-10 16:32 UTC
## Overview

adidas is listed twice as a Contributor on facility number VN2019085P645QS.

### Expected Behavior

adidas has uploaded two different lists to the platform, each with different names. Even if this facility appears on both of their lists, should their two contributor entries not show as different names? 

### Actual Behavior

adidas appears twice, simply as "adidas". 

By comparison, if you filter a search of the OAR by Contributor "Wikirate" and then select the first two entries on the scrolling panel, their appearance on the Contributor list shows the different names of their facility lists, rather than just "Wikirate". 

### Steps to Reproduce

* Search VN2019085P645QS
* View the list of Contributors on the profile: adidas appears twice at the bottom.

### Demo

![Screenshot 2019-12-10 at 16 23 21](https://user-images.githubusercontent.com/46344729/70548330-42d59b80-1b6a-11ea-8228-8d9ac086190a.png)

Clicking through first entry of "adidas":

![Screenshot 2019-12-10 at 16 23 29](https://user-images.githubusercontent.com/46344729/70548363-51bc4e00-1b6a-11ea-807d-6b80fd643857.png)

Clicking through second entry of "adidas":

![Screenshot 2019-12-10 at 16 23 42](https://user-images.githubusercontent.com/46344729/70548383-5a148900-1b6a-11ea-9f7b-bed1c40c8fd8.png)

**Comment by jwalgran** [comment] 2019-12-10 16:42
This can happen if a contributor uploads two lists, both containing the same facility. In this case, both lists are probably named "adidas" so you can't tell the difference between the listings.

We could change the way we list Contributors so that we only show one entry per contributor account, but we need to answer a questions. Right now we show the name of the list next to the supplier name. In the situation where the Contributor has uploaded multiple lists that contain the same facility, what should we show? Some options:

- All the list names
```
* adidas (adidas, adidas)
```
or
```
* adidas
  * adidas
  * adidas
```
- The most recent, and a count.
```
* adidas (adidas and 1 other list)
```

**Comment by katieashaw** [comment] 2019-12-11 13:30
Apologies, this was my miss that the list names are identical, although their descriptions are different. Looping @nataliegrillon in on this so we can discuss together on our call later. 

As well as the options described above, is there a way each Contributor link could direct you to the specific facility list on the Contributor profile?

**Comment by jwalgran** [comment] 2019-12-11 17:48
We reviewed this as a group and discovered that the duplication was caused by two entries from the same list. We have decided to close this issue because:
* The duplication is a moderation concern, not a code bug.
* We agreed that we want to be able to see when duplication like this appears in the future so that it can be added to the moderation list.

**Closed by jwalgran** 2019-12-11 17:48 UTC
Labels: bug
