### ISSUE TITLE
New text for Contribute page to more explicitly guide people to confirm / reject step

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1017] opened 2020-05-14 15:52 UTC
## Overview

I'd like to update the text on the Contribute page, to more explicitly guide users to the confirm / reject step of contributing data to the tool.

### Is your feature request related to a problem? Please describe.

A significant number of users are not completing the confirm / reject step when contributing data.

### Describe the solution you'd like

Updated text (I can write this, when you're ready) on the Contribute page to guide people to this step in the upload process.

**Comment by dboyer** [comment] 2020-11-06 14:53
Closing as duplicate of #1164

**Closed by dboyer** 2020-11-06 14:53 UTC
Labels: high priority
