### ISSUE TITLE
Foreign language accents not rendering correctly 

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#113] opened 2019-01-22 10:53 UTC
## Overview

Supplier lists uploaded to the OAR cover a wide range of languages and therefore include many foreign characters and accents. Across multiple lists, these characters and accents are not rendering correctly and appear as question marks.

### Expected Behavior

When lists are uploaded which include words with foreign language accents and characters, these should be visible on the site in their original form. 

### Actual Behavior

Foreign language accents often appear as question marks.

### Steps to Reproduce

* Filter a search on the site by a country such as Brazil or Turkey
* Select some facilities to view the address details and you will encounter many which include accents which have rendered incorrectly

OR

* Filter your search by "Seed Factories" and whichever has the most current date (apologies, I can't access the site now to give you the exact example I'm thinking of)
* This list includes facilities where the accents aren't rendering correctly in the addresses

### Demo

Here's a screenshot which includes accents not rendering correctly:

https://drive.google.com/open?id=1aGylnZ9fnGTMayWic4tzDKRQu__WDzgn

### Additional context

A fix for some lists was implemented prior to the October launch, but does not seem to apply to all lists uploaded to the site - i.e. we have uploaded lists since this fix was written, but it hasn't worked on the newer lists.

**Comment by katieashaw** [comment] 2019-06-04 09:38
We have received feedback this month on Turkish characters not rendering correctly on the front end of the site. See screenshot for an example: 

![Screenshot 2019-06-03 at 16 55 43](https://user-images.githubusercontent.com/46344729/58868747-df4b4c80-86b4-11e9-9a15-ae8370af41b6.png)

**Comment by jwalgran** [comment] 2019-06-05 17:47
I looked in the database and confirmed the original CSV line looks like what is appearing in the screenshot.

```
Turkey,ORTA ANADOLU TIC. VE SAN. ISL. TAS,ORGAN?ZE SANAYI BOLGES? 24.CAD. NO:51 MEL?KGAZI KAYSERI  KAYSERI  34373
```

This was likely an issue with the content of the original file or the way in which the OAR code read the original file.

**Comment by katieashaw** [comment] 2019-06-05 17:54
Oh, interesting - thanks for checking!

**Comment by jwalgran** [comment] 2019-10-28 15:32
Closing because this is not an issue with the application.

**Closed by jwalgran** 2019-10-28 15:32 UTC
Labels: frontend
