### ISSUE TITLE
Analysis of Code and Risk Assessment of Migrating to new Environment 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2391] opened 2023-03-29 14:47 UTC
**User Story:** 
As a member of the OS Hub development team, I want to make sure that we can understand any 3rd party tools / accounts that are being used in the development, staging, or production environments of OS Hub so that I can transition these areas of the application to other tools or take over the account from the E84 team and successfully administer and maintain the application by the end of May. 

**Expected Solution: **
1) Conduct an audit of 3rd party tools / accounts and document where in the application the tool is used and for what purpose 
2) Propose that this be time boxed to 4 hours (please advise if this would be insufficient) 

**Additional Context:** 
Azavea has deep knowledge of the technical stack and application as they have been the primary developers since 2019. They have already done a preliminary review for 3rd party tools / accounts as listed [here](https://docs.google.com/document/d/1OSCPSJSAiMOCoQjlG__bCEu4RyXBDMi6sGEct2KTMXg/edit#). This ticket is for them to do another check for any other tools / accounts that should be transferred to OS Hub.

**Comment by jwalgran** [comment] 2023-03-30 15:50
@mariel-oar To get a better sense of the scope of the issue could you please provide answers to the following:
- What should the deliverable be? Google Doc? Presentation?
- What level of details is required?
- The story is written "As a product manager." Are you the sole audience and what level of technical detail is desired?
- Is there a limit on the amount of time that should be spent on this.

(Since I am asking guiding questions for this issue I labeled it client action needed)

**Comment by mariel-oar** [comment] 2023-04-01 01:37
Thanks @jwalgran , let me discuss the time box with Klaus. It's a great point. I added some specifics above, but imagine we might want to pull in a few more specific questions for your to cover. Will look to close this early next week. 

And re: audience, it's the development team in general. Level of technical detail should reflect the level of detail that you would discuss these topics with a peer.

**Comment by obrienad** [comment] 2023-04-05 15:02
Mariel confirmed timebox

**Comment by obrienad** [comment] 2023-05-10 15:30
Closing this as it was addressed in knowledge transfer / transfer conversations.

**Closed as completed by obrienad** 2023-05-10 15:30 UTC
