### ISSUE TITLE
Address Python version deprecation warnings in build output

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#249] opened 2019-03-05 16:13 UTC
## Overview

The CI build output contains warnings about a deprecated Python version

>/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.

We are using Python 3 in our actual application containers, but the dev/build VM currently runs 2.7.12.

### Expected Behavior

The CI build output is free of Python version warnings.

### Actual Behavior

The CI build output contains version warnings

What happens instead of the expected behavior?

### Steps to Reproduce

* Run `./scripts/cibuild`

**Comment by hectcastro** [comment] 2019-03-06 15:17
This is intended to resolve warning on `civicci01` only, right? I was enable to reproduce the warnings in the local development VM.

For `civicci01`, https://github.com/azavea/operations/issues/291 may take care of this issue as well.

**Comment by jwalgran** [comment] 2019-03-07 21:01
Yes, this is intended to resolve warnings on `civicci01` only.

**Comment by hectcastro** [comment] 2019-03-11 22:17
Closed via https://github.com/azavea/operations/issues/291.

**Closed by hectcastro** 2019-03-11 22:17 UTC
Labels: bug, operations, queue
