### ISSUE TITLE
November figures for Percent Data by Source Type are way off

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1554] opened 2021-12-09 08:18 UTC
## Overview

Looking at this report: https://openapparel.org/admin/reports/percent-data-by-source-type/

The percentages between Single and List submissions usually add up to roughly 100%. For November 2021, that figure was way off:

![Screen Shot 2021-12-09 at 9 17 53 AM](https://user-images.githubusercontent.com/80268596/145359479-73e64bab-f13e-4edd-9c87-c519e96058d1.png)

We would love to understand why the numbers are so different for this month and if they are accurate. We will need an answer to this by mid-January 2022 (Jan 14 at the latest), so we can finalize reporting for funders.

**Comment by hlennett** [comment] 2021-12-09 08:24
cc @katieashaw

**Comment by katieashaw** [comment] 2022-01-07 15:47
Flagging this for @obrienad & @jwalgran giving the up-coming deadline

**Comment by jwalgran** [comment] 2022-01-10 15:16
We added this issue to the current sprint are are working on debugging the query behind this report.

**Comment by TaiWilkin** [comment] 2022-01-10 17:49
I have identified the cause of the data issue. A fix is in-process, but meanwhile we will manually pull a corrected version of the data for the OAR team. 

For each facility, we look at all the times it was submitted and it was successfully matched / created. Some facilities were submitted multiple times by the same contributor, but we don’t want to count duplicates / resubmissions. 

An example of a single facility’s many submissions pre-filtering (data anonymized with false IDs):
<img width="225" alt="Screen Shot 2022-01-10 at 12 43 38 PM" src="https://user-images.githubusercontent.com/21046714/148813125-413db328-8eed-465a-b5da-410b9b0b77b3.png">

When filtering to look at only the initial submission by each contributor, we were filtering the submissions in two different ways when calculating the number of submissions for each source type vs calculating the total number of submissions. 

When calculating the number of facilities submitted via each source type per month, we were asking: What was the first time this contributor submitted this facility via this source? By this measure, you can see that contributor 2 is considered to have submitted the facility twice - once by list in February 2020 and once by API in November 2021. Counting this way, the facility was submitted three times (twice by list and once by API) in November.
<img width="229" alt="Screen Shot 2022-01-10 at 12 44 14 PM" src="https://user-images.githubusercontent.com/21046714/148813210-c4b0a628-9b1f-4c83-9716-eaf95436ebc8.png">

When calculating the total number of facilities submitted per month, we were asking: What was the first time this contributor submitted this facility? By this measure, contributor 2 only submitted the facility once (in February 2020) - their change from using list submission to using API submission isn’t tracked. Counting this way, the facility was submitted twice (both by list) in November.
<img width="232" alt="Screen Shot 2022-01-10 at 12 44 45 PM" src="https://user-images.githubusercontent.com/21046714/148813276-4f1acdb7-33d0-4322-aed9-927eca23f063.png">

When returning the report results, we would get the numbers 100.00% for List (2 out of 2) and 50.00% for API/Single (1 out of 2) in the above situation. 

Generally, contributors are (mostly) consistent in which type of source they use. However, in November 2021, one contributor in particular resubmitted ~2000 facilities, which they had previously submitted via list, using the API. These facilities were counted in the calculation of number of API submissions for the month, but were incorrectly skipped when calculating the total number of facility submissions for the month. 

In order to correct this error, we are updating the report to count each contributor’s initial submission of the facility via each source type for both the source_type count and the total count. This will result in a more accurate representation of the percentage of submissions coming from each source type per month. 

When returning the report results, we would now get 66.66% (2 out of 3) for List and 33.33% (1 out of 3) for Single for the above example, correctly indicating the switch to API usage by contributor 2.

**Closed** 2022-01-20 17:28 UTC
Labels: bug, high priority
