### ISSUE TITLE
Map not displaying widths between 600 and 1280

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2260] opened 2022-10-20 13:59 UTC
## Overview
In the EM test site and on the setting pages of users who have an EM set up, there is no map displayign on the map tab. See screen recording: 
https://images.zenhubusercontent.com/159699912/db1f7b98-b8e7-457f-9f11-d7e0b7504ed8/screen_recording_2022_10_20_at_9_56_43_am.mov

### Expected Behavior

Map should display similar to the map that displays when you enter "&embed=1" at the end of URL 
Map that displays shows the settings that the contributor has configured in their settings 

### Actual Behavior

What happens instead of the expected behavior?

### Steps to Reproduce
Go to: https://open-apparel-registry.github.io/embeded-map-test-fixed-size.html?host=prd.fb84e0f7529f2737.openapparel.org&contributors=540 
See that map tab is blank.

**Comment by jwalgran** [comment] 2022-10-20 15:43
I changed the title of this issue to "Map not displaying in mobile view" because it is not just a problem with embedded maps. I was able to reproduce it in the regular mobile view.

**Comment by TaiWilkin** [comment] 2022-10-21 19:30
I can't replicate this on production, so it's likely one of the few PRs we've merged over the last week. [#2250](https://github.com/open-apparel-registry/open-apparel-registry/pull/2250) seems a likely culprit.

**Comment by jwalgran** [comment] 2022-10-21 20:45
I can replicate this in production


https://user-images.githubusercontent.com/17363/197285591-b78d978a-bf36-4bdc-9044-0e0c1fc4653b.mp4

**Comment by jwalgran** [comment] 2022-10-21 20:50
More specifically is looks like the issue is the "middle" width between 600px and 1280px


https://user-images.githubusercontent.com/17363/197286378-e5a4d619-fc53-4572-a910-0212b8dd87a6.mp4

**Comment by jwalgran** [comment] 2022-10-21 21:52
I started from `ogr/master` and worked backwards until the map was visible at middle widths. It appears that the introduction of the new footer in #2189 is when the map stopped appearing at middle widths.

**Closed as completed** 2022-10-27 19:38 UTC
Labels: bug, +, Task 60
