### ISSUE TITLE
Enable contributors to replace individual facilities which have produced a geo-code error when they access better address details

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#794] opened 2019-09-10 10:28 UTC
## Overview

When users receive a geo-code error message for facilities on their lists, many are following up by sourcing better quality address details for those facilities. Is there a way to streamline the process of updating these address details on their lists? 

### Is your feature request related to a problem? Please describe.

Users would like to edit entries within their lists which have produced a geo-code error once they have accessed better quality address information. Currently they can only do this by uploading a new list containing those specific facilities / uploading an entirely new list with those entries corrected. 

### Describe the solution you'd like

Is it possible to develop a way for users to be able to go into their existing lists and edit individual facilities within the list which have produced a geo-code result?

### Additional Context

The Dutch Covenant (AGT) is one user that has made this request.

**Comment by jwalgran** [comment] 2021-03-18 17:39
duplicate of #1182

**Closed by jwalgran** 2021-03-18 17:39 UTC
Labels: feedback, high priority
