### ISSUE TITLE
Automated email to be sent to Contributors when processing of their upload is complete

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#996] opened 2020-03-19 19:07 UTC
## Overview

We would like Contributors to be sent an automated email letting them know when the processing of their upload is complete.

### Is your feature request related to a problem? Please describe.

With the amount of time it takes for a list to process depending on multiple factors, including the length of the list, many users leave their list processing in the background and go off to work on other things. We suspect that many users then forget to check back on when the processing is complete and so don't review their list and go through the confirm / reject process, or look at error messages. This email would serve as a prompt to complete the full upload process. 

### Describe the solution you'd like

An automated email to be sent to users when processing of their upload is complete. 

### Additional Context

I can provide text for the email, which sets out to Contributors what they need to do next, include links to the FAQs on confirm / reject etc.

**Comment by dboyer** [comment] 2020-05-25 15:22
Closing as duplicate of #928

**Closed by dboyer** 2020-05-25 15:22 UTC
