### ISSUE TITLE
Suppress "pure-python SequenceMatcher" warning

### ISSUE THREAD

**Issue by nanotubing** [open-apparel-registry/open-apparel-registry#2009] opened 2022-07-29 15:49 UTC
when using [thefuzz](https://github.com/seatgeek/thefuzz), this warning is output very frequently from scripts such as `resetdb`, but the performance issue does not cause a serious problem based on our use of this library. We should suppress this warning while we decide on whether a more permanent solution makes sense for this project.

`/usr/local/lib/python3.7/site-packages/thefuzz/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning`

**Comment by rajadain** [comment] 2022-07-29 15:57
Possible duplicate of #1733?

**Closed** 2022-08-04 20:08 UTC
Labels: +
